all:
	make --no-print-directory -f OVL_ONE_COLD_Makefile
	make --no-print-directory -f OVL_ONE_HOT_Makefile
	
clean:
	  rm -fr a.out *.log *.vcd tee

help:
	make --no-print-directory -f OVL_ONE_COLD_Makefile help
	make --no-print-directory -f OVL_ONE_HOT_Makefile  help

